BlogBundle\Entity\Menu:
    type: entity
    table: menu
    id:
        id:
            type: boolean
            nullable: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        position:
            type: boolean
            nullable: false
        slug:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
    lifecycleCallbacks: {  }
