BlogBundle\Entity\Posts:
    type: entity
    table: posts
    indexes:
        user_id:
            columns:
                - user_id
        cat_id:
            columns:
                - cat_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        userId:
            type: bigint
            nullable: true
            options:
                unsigned: true
            column: user_id
        catId:
            type: integer
            nullable: true
            options:
                unsigned: true
            column: cat_id
        title:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        photo:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        content:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        excerpt:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        viewCount:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: view_count
        createdAt:
            type: datetime
            nullable: true
            options:
                default: CURRENT_TIMESTAMP
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
        postType:
            type: string
            nullable: false
            length: null
            options:
                fixed: false
            column: post_type
    lifecycleCallbacks: {  }
