BlogBundle\Entity\Users:
    type: entity
    table: users
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        email:
            type: string
            nullable: false
            length: 40
            options:
                fixed: false
        username:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        avatar:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
        fname:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        lname:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        password:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        salt:
            type: string
            nullable: true
            length: 60
            options:
                fixed: false
        createDate:
            type: datetime
            nullable: true
            column: create_date
    lifecycleCallbacks: {  }
